[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "pages-stack-db"
database_id = "705c2c5f-de8c-4738-8f21-57b0825fcf05"
migrations_dir = "./migrations"

[vars]
REDIRECT_URI = "http://localhost:8788/api/auth/callback"